//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventWatcher.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class events
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public events()
        {
            this.SeatsStatus = new HashSet<SeatsStatus>();
        }
    
        public long id { get; set; }
        public Nullable<long> location_id { get; set; }
        public Nullable<long> event_type_id { get; set; }
        public Nullable<long> details_id { get; set; }
        public Nullable<decimal> price { get; set; }
    
        public virtual descryptions descryptions { get; set; }
        public virtual events_types events_types { get; set; }
        public virtual locations locations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SeatsStatus> SeatsStatus { get; set; }
    }
}
