//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EventWatcher.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class event_watcher_dbEntities : DbContext
    {
        public event_watcher_dbEntities()
            : base("name=event_watcher_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<descryptions> descryptions { get; set; }
        public virtual DbSet<events> events { get; set; }
        public virtual DbSet<events_types> events_types { get; set; }
        public virtual DbSet<locations> locations { get; set; }
        public virtual DbSet<SeatsStatus> SeatsStatus { get; set; }
    }
}
